# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import snn_pb2 as snn__pb2


class SnnStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Init = channel.unary_stream(
        '/snn.Snn/Init',
        request_serializer=snn__pb2.InitRequest.SerializeToString,
        response_deserializer=snn__pb2.InitResponse.FromString,
        )
    self.Run = channel.unary_stream(
        '/snn.Snn/Run',
        request_serializer=snn__pb2.RunRequest.SerializeToString,
        response_deserializer=snn__pb2.RunResponse.FromString,
        )
    self.Runwithcheck = channel.unary_stream(
        '/snn.Snn/Runwithcheck',
        request_serializer=snn__pb2.RunRequest.SerializeToString,
        response_deserializer=snn__pb2.RunResponse.FromString,
        )
    self.Measure = channel.unary_stream(
        '/snn.Snn/Measure',
        request_serializer=snn__pb2.MetricRequest.SerializeToString,
        response_deserializer=snn__pb2.MetricResponse.FromString,
        )
    self.Updateprop = channel.stream_unary(
        '/snn.Snn/Updateprop',
        request_serializer=snn__pb2.UpdatePropRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdatePropResponse.FromString,
        )
    self.Updategamma = channel.stream_unary(
        '/snn.Snn/Updategamma',
        request_serializer=snn__pb2.UpdateGammaRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdateGammaResponse.FromString,
        )
    self.Updategammawithresult = channel.stream_stream(
        '/snn.Snn/Updategammawithresult',
        request_serializer=snn__pb2.UpdateGammaRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdateGammaWithResultResponse.FromString,
        )
    self.Updatehyperpara = channel.stream_unary(
        '/snn.Snn/Updatehyperpara',
        request_serializer=snn__pb2.UpdateHyperParaRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdateHyperParaResponse.FromString,
        )
    self.Updatesample = channel.stream_unary(
        '/snn.Snn/Updatesample',
        request_serializer=snn__pb2.UpdateSampleRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdateSampleResponse.FromString,
        )
    self.Updatesamplewithcheck = channel.stream_unary(
        '/snn.Snn/Updatesamplewithcheck',
        request_serializer=snn__pb2.UpdateSampleRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdateSampleResponse.FromString,
        )
    self.Updateoubackgroundparam = channel.unary_unary(
        '/snn.Snn/Updateoubackgroundparam',
        request_serializer=snn__pb2.UpdateOUBackgroundParamRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdateOUBackgroundParamResponse.FromString,
        )
    self.Updatettypecacurrentparam = channel.stream_unary(
        '/snn.Snn/Updatettypecacurrentparam',
        request_serializer=snn__pb2.UpdateTTypeCaCurrentParamRequest.SerializeToString,
        response_deserializer=snn__pb2.UpdateTTypeCaCurrentParamResponse.FromString,
        )
    self.Checksampleconnweight = channel.unary_unary(
        '/snn.Snn/Checksampleconnweight',
        request_serializer=snn__pb2.CheckSampleConnWeightRequest.SerializeToString,
        response_deserializer=snn__pb2.CheckSampleConnWeightResponse.FromString,
        )
    self.Loadstatefromfile = channel.unary_unary(
        '/snn.Snn/Loadstatefromfile',
        request_serializer=snn__pb2.LoadStateRequest.SerializeToString,
        response_deserializer=snn__pb2.LoadStateResponse.FromString,
        )
    self.Setstaterule = channel.unary_unary(
        '/snn.Snn/Setstaterule',
        request_serializer=snn__pb2.SetStateRuleRequest.SerializeToString,
        response_deserializer=snn__pb2.SetStateRuleResponse.FromString,
        )
    self.Shutdown = channel.unary_unary(
        '/snn.Snn/Shutdown',
        request_serializer=snn__pb2.ShutdownRequest.SerializeToString,
        response_deserializer=snn__pb2.ShutdownResponse.FromString,
        )


class SnnServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Init(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Runwithcheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Measure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updateprop(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updategamma(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updategammawithresult(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updatehyperpara(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updatesample(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updatesamplewithcheck(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updateoubackgroundparam(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Updatettypecacurrentparam(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Checksampleconnweight(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Loadstatefromfile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Setstaterule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Shutdown(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SnnServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Init': grpc.unary_stream_rpc_method_handler(
          servicer.Init,
          request_deserializer=snn__pb2.InitRequest.FromString,
          response_serializer=snn__pb2.InitResponse.SerializeToString,
      ),
      'Run': grpc.unary_stream_rpc_method_handler(
          servicer.Run,
          request_deserializer=snn__pb2.RunRequest.FromString,
          response_serializer=snn__pb2.RunResponse.SerializeToString,
      ),
      'Runwithcheck': grpc.unary_stream_rpc_method_handler(
          servicer.Runwithcheck,
          request_deserializer=snn__pb2.RunRequest.FromString,
          response_serializer=snn__pb2.RunResponse.SerializeToString,
      ),
      'Measure': grpc.unary_stream_rpc_method_handler(
          servicer.Measure,
          request_deserializer=snn__pb2.MetricRequest.FromString,
          response_serializer=snn__pb2.MetricResponse.SerializeToString,
      ),
      'Updateprop': grpc.stream_unary_rpc_method_handler(
          servicer.Updateprop,
          request_deserializer=snn__pb2.UpdatePropRequest.FromString,
          response_serializer=snn__pb2.UpdatePropResponse.SerializeToString,
      ),
      'Updategamma': grpc.stream_unary_rpc_method_handler(
          servicer.Updategamma,
          request_deserializer=snn__pb2.UpdateGammaRequest.FromString,
          response_serializer=snn__pb2.UpdateGammaResponse.SerializeToString,
      ),
      'Updategammawithresult': grpc.stream_stream_rpc_method_handler(
          servicer.Updategammawithresult,
          request_deserializer=snn__pb2.UpdateGammaRequest.FromString,
          response_serializer=snn__pb2.UpdateGammaWithResultResponse.SerializeToString,
      ),
      'Updatehyperpara': grpc.stream_unary_rpc_method_handler(
          servicer.Updatehyperpara,
          request_deserializer=snn__pb2.UpdateHyperParaRequest.FromString,
          response_serializer=snn__pb2.UpdateHyperParaResponse.SerializeToString,
      ),
      'Updatesample': grpc.stream_unary_rpc_method_handler(
          servicer.Updatesample,
          request_deserializer=snn__pb2.UpdateSampleRequest.FromString,
          response_serializer=snn__pb2.UpdateSampleResponse.SerializeToString,
      ),
      'Updatesamplewithcheck': grpc.stream_unary_rpc_method_handler(
          servicer.Updatesamplewithcheck,
          request_deserializer=snn__pb2.UpdateSampleRequest.FromString,
          response_serializer=snn__pb2.UpdateSampleResponse.SerializeToString,
      ),
      'Updateoubackgroundparam': grpc.unary_unary_rpc_method_handler(
          servicer.Updateoubackgroundparam,
          request_deserializer=snn__pb2.UpdateOUBackgroundParamRequest.FromString,
          response_serializer=snn__pb2.UpdateOUBackgroundParamResponse.SerializeToString,
      ),
      'Updatettypecacurrentparam': grpc.stream_unary_rpc_method_handler(
          servicer.Updatettypecacurrentparam,
          request_deserializer=snn__pb2.UpdateTTypeCaCurrentParamRequest.FromString,
          response_serializer=snn__pb2.UpdateTTypeCaCurrentParamResponse.SerializeToString,
      ),
      'Checksampleconnweight': grpc.unary_unary_rpc_method_handler(
          servicer.Checksampleconnweight,
          request_deserializer=snn__pb2.CheckSampleConnWeightRequest.FromString,
          response_serializer=snn__pb2.CheckSampleConnWeightResponse.SerializeToString,
      ),
      'Loadstatefromfile': grpc.unary_unary_rpc_method_handler(
          servicer.Loadstatefromfile,
          request_deserializer=snn__pb2.LoadStateRequest.FromString,
          response_serializer=snn__pb2.LoadStateResponse.SerializeToString,
      ),
      'Setstaterule': grpc.unary_unary_rpc_method_handler(
          servicer.Setstaterule,
          request_deserializer=snn__pb2.SetStateRuleRequest.FromString,
          response_serializer=snn__pb2.SetStateRuleResponse.SerializeToString,
      ),
      'Shutdown': grpc.unary_unary_rpc_method_handler(
          servicer.Shutdown,
          request_deserializer=snn__pb2.ShutdownRequest.FromString,
          response_serializer=snn__pb2.ShutdownResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'snn.Snn', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
